title: Tomoya Wakayama
email: tom-w9@g.ecc.u-tokyo.ac.jp
description: Ph.D. candidate, Department of Statistics, Graduate School of Economics, The University of Tokyo
url: "https://yourusername.github.io"
baseurl: ""
twitter_username: yourusername
github_username:  yourusername

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Build settings  
theme: minima
plugins:
  - jekyll-feed
