# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
locale                   : "en-US"
title                    : "Tomoya Wakayama"
title_separator          : "-"
name                     : "Tomoya Wakayama"
description              : "Postdoctoral Researcher, Deep Learning Theory Team, RIKEN AIP"
url                      : "https://tomwaka.github.io"
baseurl                  : ""
repository               : "TomWaka/TomWaka.github.io"

# Site Author
author:
  name             : "Tomoya Wakayama"
  avatar           : "images/44727480.jpeg"
  bio              : "若山 智哉"
  location         : "Tokyo, Japan"
  employer         : "RIKEN Center for Advanced Intelligence Project"
  googlescholar    : "https://scholar.google.com/citations?user=2C30Kn8AAAAJ"
  email            : "tomoya.wakayama@riken.jp"
  github           : "TomWaka"
  twitter : "10m8mkW"

# Site Settings  
breadcrumbs              : false 
words_per_minute         : 160
future                   : true
read_more                : "disabled" 
talkmap_link             : false
comments:
  provider               : 
  disqus:
    shortname            :
  discourse:
    server               : 
  facebook:
    appid                :
    num_posts            : 
    colorscheme          : 
atom_feed:
  hide                   : false   

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Analytics
analytics:
  provider               : false 
  google:
    tracking_id          :

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  publications:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/
  teaching:
    output: true
    permalink: /:collection/:path/    

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true      

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed 

# Outputting
permalink: /:categories/:title/
timezone: Asia/Tokyo 

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
